# Generated by Django 4.2 on 2025-11-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='info',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Info'),
        ),
    ]
