# Generated by Django 4.2 on 2025-11-27 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productimages_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='info',
        ),
    ]
